image:
- Visual Studio 2019 Preview
- macos
skip_commits:
  message: /docs|Merge pull request.*/
test: off
artifacts:
- path: nugets\*.nupkg

for:
  -
    matrix:
      only:
        - image: Visual Studio 2019 Preview
    build_script:
      - ps: >-
          dotnet build src/DiffEngine.sln --configuration Release

          dotnet test src/DiffEngine.sln --configuration Release --no-build --no-restore --filter Category!=Integration

  -
    matrix:
      only:
        - image: macos
    build_script:
      - ps: >-
          dotnet build src --configuration MacOs

          dotnet test src --configuration MacOs --no-build --no-restore --filter Category!=Integration

on_failure:
  - ps: Get-ChildItem *.received.* -recurse | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }